# Generated by Django 3.1.2 on 2021-07-29 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210729_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=5, unique=True),
        ),
    ]
