# Generated by Django 3.1.2 on 2021-07-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_courierpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.courierpartner'),
        ),
    ]
