# Generated by Django 3.1.2 on 2021-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_order_courier_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierpartner',
            name='track_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
