# Generated by Django 3.1.2 on 2021-07-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20210729_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierpartner',
            name='track_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_key',
        ),
        migrations.CreateModel(
            name='TrackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('courier_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.courierpartner')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='track_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.trackdetail'),
        ),
    ]
