# Generated by Django 3.1.2 on 2021-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20210729_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackdetail',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackdetail',
            name='is_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackdetail',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
