# Generated by Django 3.1.2 on 2021-07-29 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_trackdetail_is_out_for_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackdetail',
            name='time_stamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
