# Generated by Django 3.1.2 on 2021-07-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_trackdetail_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdetail'),
        ),
    ]
