# Generated by Django 3.1.2 on 2021-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20210729_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
